# Generated by Django 3.2.6 on 2021-08-18 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя и Фамилия автора')),
                ('excerpt', models.TextField(max_length=300, verbose_name='Краткое описание преимуществ / интересов автора')),
                ('thumbnail', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Фото')),
                ('content', models.TextField(verbose_name='Контент')),
            ],
            options={
                'verbose_name': 'Страница об авторе',
                'verbose_name_plural': 'Страница об авторе',
            },
        ),
    ]
