# Generated by Django 3.2.6 on 2021-08-18 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='email',
            field=models.EmailField(default='guldmytro@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
