# Generated by Django 3.2.6 on 2021-08-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210816_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.TextField(default='short', max_length=150, verbose_name='Краткое описание'),
            preserve_default=False,
        ),
    ]
