# Generated by Django 3.2.6 on 2021-08-18 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_excerpt'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='thumbnail',
            field=models.FileField(blank=True, help_text='Поддерживаются форматы: .png, .jpg, .svg', null=True, upload_to='images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.TextField(max_length=500, verbose_name='Краткое описание'),
        ),
    ]
